name: Makefile CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./scripts/feeds update -a && ./scripts/feeds install -a && cp diffconfig .config && make defconfig && ./scripts/getver.sh

    - name: Install dependencies
      run: make V=s

    - name: Upload directories
      uses: actions/upload-artifact@main
      with:
        name: build_upload
        path: |
          bin

    - name: Run check
      run: make check

#    - name: Run distcheck
#      run: make distcheck
